name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: check out repo
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: setup poetry
        run: |
          python -m pip install poetry==1.2.1
          python -m poetry install

      - name: run tests
        shell: bash
        run: python -m poetry run python -m pytest